// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsJz7eAPY8uHIUC_LccCL1YuAqiuA1vg8',
    appId: '1:160425369268:web:e8253fbf0590e43e3a41e1',
    messagingSenderId: '160425369268',
    projectId: 'fhainspectorapp-9dde8',
    authDomain: 'fhainspectorapp-9dde8.firebaseapp.com',
    storageBucket: 'fhainspectorapp-9dde8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFi51n3TtGKBSsylwnlLE3v9sMEgpZZqI',
    appId: '1:160425369268:android:a03df6abb49012fb3a41e1',
    messagingSenderId: '160425369268',
    projectId: 'fhainspectorapp-9dde8',
    storageBucket: 'fhainspectorapp-9dde8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDax3WT0omjdlOn_KFsYHCR0x_VT95VNEY',
    appId: '1:160425369268:ios:76b50761c992970e3a41e1',
    messagingSenderId: '160425369268',
    projectId: 'fhainspectorapp-9dde8',
    storageBucket: 'fhainspectorapp-9dde8.firebasestorage.app',
    iosBundleId: 'com.fhainspector.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDax3WT0omjdlOn_KFsYHCR0x_VT95VNEY',
    appId: '1:160425369268:ios:2390e485cddbfe933a41e1',
    messagingSenderId: '160425369268',
    projectId: 'fhainspectorapp-9dde8',
    storageBucket: 'fhainspectorapp-9dde8.firebasestorage.app',
    iosBundleId: 'com.example.artneidichApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsJz7eAPY8uHIUC_LccCL1YuAqiuA1vg8',
    appId: '1:160425369268:web:30efdcca01c66ee83a41e1',
    messagingSenderId: '160425369268',
    projectId: 'fhainspectorapp-9dde8',
    authDomain: 'fhainspectorapp-9dde8.firebaseapp.com',
    storageBucket: 'fhainspectorapp-9dde8.firebasestorage.app',
  );
}
